#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=40,walltime=100:00:00
#PBS -M ahuxford@anl.gov
#PBS -m abe
#PBS -N 1int_InVOutP_sep
#PBS -j oe
#PBS -q eddy40core

cd $PBS_O_WORKDIR

module purge

module load moose/.mpich-3.3_gcc-9.2.0
module load miniconda moose-tools

export CARDINAL_HOME=/home/cluster2/rhu/projects/NEAMS/aaron/cardinal
export NEKRS_HOME=$CARDINAL_HOME/install

export PATH=/home/cluster1/ahuxford/bin:$PATH

mpirun -np 40 $CARDINAL_HOME/cardinal-opt --app sam -i coupled_master.i --nekrs-setup pipe  > logfile
