#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=80,walltime=100:00:00
#PBS -M ahuxford@anl.gov
#PBS -m abe
#PBS -N over_nosub
#PBS -j oe
#PBS -q eddy80core

#rm -f logfile
mv $1.log.$2 $1.log1.$2 2>/dev/null

cd $PBS_O_WORKDIR

cat $PBS_NODEFILE | uniq

echo "loop" >  SESSION.NAME
echo `pwd`'/' >>  SESSION.NAME
#rm -f logfile
rm -f ioinfo

module purge
module load moose-dev-gcc

export CARDINAL_HOME=/home/cluster2/rhu/projects/NEAMS/cardinal_aaron2
export NEKRS_HOME=$CARDINAL_HOME/install

mpirun -np 80 $CARDINAL_HOME/cardinal-opt --app SAM -i coupled_master.i --nekrs-setup pipe  > logfile
